#!/usr/bin/env python2

import sys
import re

ddl = sys.stdin.read()

patt = re.compile(r"^(CREATE MATERIALIZED VIEW (?:.*?)\n\n)", re.MULTILINE | re.DOTALL)
mvs = patt.findall(ddl)

for mv in mvs:
    print(mv)
