#!/usr/bin/env python2

import sys
import re

ddl = sys.stdin.read()

patt = re.compile(r"^(CREATE MATERIALIZED VIEW (?:.*?)(?:\n\n|\Z))", re.MULTILINE | re.DOTALL)
mvs = patt.findall(ddl)

def del_mv (mv):
  mvn_patt = re.compile(r"^CREATE MATERIALIZED VIEW\s+([^\s]+)\s+(?:.*?)$", re.MULTILINE | re.DOTALL)
  mvn = mvn_patt.findall(mv)[0]
  return "DROP MATERIALIZED VIEW IF EXISTS " + mvn + ";\n\n"

drop_mvs = map(del_mv, mvs)

for dmv in drop_mvs:
    print(dmv)
